name: plasgraph
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # More stable with packages like torch-geometric
  - pip
  - scikit-learn=1.6.1
  - optuna=4.3.0
  - numpy=1.26.4
  - pandas=2.2.3
  - matplotlib=3.10.3
  - pyyaml=6.0.2
  - torch-geometric
  - transformers
  - networkx
  - seaborn
  - biopython
  - plotly
  - pip:
      - torch==2.7.1
      - torchvision
      - torchaudio
      - kaleido
      - --extra-index-url https://download.pytorch.org/whl/cu121
