name: plasgraph
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch>=2.6
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - scikit-learn=1.6.1
  - optuna=4.3.0
  - numpy=2.2.3
  - pandas=2.2.3
  - matplotlib=3.10.3
  - pyyaml=6.0.2
  - torch-geometric
  - transformers
  - networkx
  - seaborn
  - biopython
  - plotly
  - pip:
    - kaleido
